export const data = [
  { "id": 0, "value": "Provalvemente" },
  { "id": 1, "value": "Com toda certeza" },
  { "id": 2, "value": "Negativo" },
  { "id": 3, "value": "Positivo" },
  { "id": 4, "value": "Nem pensar" },
  { "id": 5, "value": "Sinceramente...não sei" },
  { "id": 6, "value": "Pode acontecer" },
  { "id": 7, "value": "Impossível" },
  { "id": 8, "value": "Improvável" },
  { "id": 9, "value": "Quem sabe um dia" },
  { "id": 10, "value": "Salve!" },
  { "id": 11, "value": "Aguarde mais..." },
  { "id": 12, "value": "Quem acredita sempre alcança" },
  { "id": 13, "value": "Siiim!" },
  { "id": 14, "value": "Nãao!" },
  { "id": 15, "value": "Com certeza" },
  { "id": 16, "value": "Naturalmente" },
  { "id": 17, "value": "Seguramente" },
  { "id": 18, "value": "Talvez um dia" },
  { "id": 19, "value": "Bem capaz" },
  { "id": 20, "value": "Olha, é provável" },
  { "id": 21, "value": "Claro" },
  { "id": 22, "value": "Não tenho certeza..." },
  { "id": 23, "value": "Balela" },
  { "id": 24, "value": "Afirmativo" },
  { "id": 25, "value": "Certo" },
  { "id": 26, "value": "Vai fundo!" }
]